### ISSUE TITLE
API documentation out of sync with module vars/outputs.

### ISSUE THREAD

**Issue by davidjeddy** [clouddrove/terraform-aws-cost-billing-alarm#6]
The [README.md](https://github.com/clouddrove/terraform-aws-cost-billing-alarm/blob/master/README.yaml) states `tags` is a valid input. Looking at the module variables.tf this is not the case. I would expect the API documentation to be re-generated on pre-commit.

**Comment by theprashantyadav** [comment]
Hello @davidjeddy 
Our team is looking into the issue.
